name: ho3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8                
  - numpy                     
  - matplotlib
  - scikit-image
  - pandas
  - opencv
  - cython
  - tqdm
  - pip
  - pip:
      - transforms3d
      - open3d
      - chumpy               # avoid git clone